require("options")
require("plugins")
require("keymap")
require("lsp")
require("autocommand")
vim.cmd("colorscheme rose-pine")
-- require("ui.colorscheme")
require("ui.terminal")
require("ui.statusline")
