-- general keymap
local map = vim.keymap.set
map("n", "<leader>o", ":update<CR> :source<CR>", { desc = "source neovim's configuration" })
map("n", "<leader>w", ":write<CR>", { desc = "write the changes made" })
map("n", "<leader>q", ":quit<CR>", { desc = "exit vim" })
map("i", "jk", "<Esc>", { desc = "exit insert mode" })
map("i", "jj", "<Esc>", { desc = "exit insert mode" })
map({ "v", "n", "x" }, "<leader>y", '"+y<CR>')
-- map({ "v", "n", "x" }, "<leader>d", '"+d<CR>')
map({ "v", "n", "x" }, "<leader>s", ":e #<CR>")
map({ "v", "n", "x" }, "<leader>S", ":sf #<CR>")
map("n", "n", "nzzzv", { desc = "Next search result (centered)" })
map("n", "N", "Nzzzv", { desc = "Previous search result (centered)" })
map("n", "<leader><esc>", ":noh<CR>", { desc = "clear search highlights" })
map("v", "<", "<gv", { desc = "Indent left and reselect" })
map("v", ">", ">gv", { desc = "Indent right and reselect" })
map("n", "<S-h>", ":bprevious<CR>", { desc = "Buffer Sebelumnya", silent = true })
map("n", "<S-l>", ":bnext<CR>", { desc = "Buffer Selanjutnya", silent = true })
map("n", "gl", vim.diagnostic.open_float, { desc = "Lihat Detail Error" })
map("n", "[d", vim.diagnostic.get_prev, { desc = "Error Sebelumnya" })
map("n", "]d", vim.diagnostic.get_next, { desc = "Error Selanjutnya" })

-- plugin keymap
vim.ui.select = require("mini.pick").ui_select
map("n", "<leader>ff", ":Pick files<CR>")
map("n", "<leader>h", ":Pick help<CR>")
map("n", "<leader>bl", ":Pick buffers<CR>", { desc = "Pick Open Buffers" })
map("n", "<leader>bd", ":bd<CR>", { desc = "Close Buffer" })
map("n", "<leader>e", function()
	require("oil").toggle_float(vim.fn.getcwd())
end, { desc = "Oil: Float Project Root" })
map("n", "<leader>fo", function()
	require("oil").toggle_float()
end, { desc = "Oil: Float Parent Directory" })
map("n", "<leader>lf", vim.lsp.buf.format)

-- mini sessions
local sessions = require("mini.sessions")
map("n", "<leader>sl", function()
	sessions.select()
end, { desc = "List Sessions" })
map("n", "<leader>ss", function()
	local name = vim.fn.input("Session Name: ")
	if name ~= "" then
		require("mini.sessions").write(name)
		vim.cmd("redraw")
		vim.api.nvim_echo({ { " 󱫐 Session '" .. name .. "' saved!", "DiagnosticInfo" } }, true, {})
	end
end, { desc = "Save Session As" })
map("n", "<leader>sd", function()
	require("mini.sessions").select("delete", { force = true })
end, { desc = "Delete Session (Force)" })
